import numpy as np
import pandas as pd
import pytest

from ..utils import analyze


@pytest.fixture
def flat_data():
    return np.zeros(10)


@pytest.fixture
def flat_data_with_impulse():
    data = np.zeros(9)
    data[5] = 1.0
    return data


def test_convolve_with_gaussian(flat_data, flat_data_with_impulse):
    y = analyze.convolve_with_gaussian(flat_data, 1.0)
    np.testing.assert_array_almost_equal(flat_data, y)
    y = analyze.convolve_with_gaussian(flat_data_with_impulse, 1.0)
    assert y[5] < flat_data_with_impulse[5]
    assert y[4] > flat_data_with_impulse[4]
    assert np.allclose(flat_data_with_impulse[0], y[0])


@pytest.mark.parametrize(
    "target, mode_hist, result",
    [
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            34.28,
                            34.1,
                            34.1,
                            34.03,
                            34.0,
                            33.97,
                            33.97,
                            33.9,
                            33.9,
                            33.9,
                            33.94,
                            33.66,
                            33.3,
                            33.2,
                            33.1,
                            33.03,
                            32.84,
                            32.97,
                            32.94,
                            32.94,
                            32.84,
                            32.8,
                            32.72,
                            32.8,
                            32.72,
                            32.75,
                            32.8,
                            32.94,
                            33.06,
                            33.3,
                            33.44,
                            33.5,
                            33.6,
                            33.62,
                            33.5,
                        ],
                        [
                            29.75,
                            29.84,
                            29.94,
                            30.02,
                            30.1,
                            30.17,
                            30.25,
                            30.33,
                            30.39,
                            30.47,
                            30.55,
                            30.62,
                            30.7,
                            30.78,
                            30.86,
                            30.89,
                            30.9,
                            30.94,
                            30.97,
                            30.98,
                            31.02,
                            31.03,
                            31.06,
                            31.08,
                            31.11,
                            31.12,
                            31.16,
                            31.22,
                            31.28,
                            31.36,
                            31.42,
                            31.5,
                            31.56,
                            31.64,
                            31.7,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "cool",
            False,
            id="Cool to Off but still cooling.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            20.75,
                            20.77,
                            20.81,
                            20.83,
                            20.81,
                            20.81,
                            20.81,
                            20.77,
                            20.73,
                            20.73,
                            20.7,
                            20.7,
                            20.8,
                            20.95,
                            21.17,
                            21.44,
                            21.58,
                            21.75,
                            21.9,
                            22.0,
                            21.92,
                            21.73,
                            21.56,
                            21.45,
                            21.31,
                            21.19,
                            21.1,
                            21.03,
                            20.97,
                            20.9,
                            20.84,
                            20.8,
                            20.75,
                            20.7,
                            20.69,
                        ],
                        [
                            24.5,
                            24.48,
                            24.47,
                            24.45,
                            24.44,
                            24.47,
                            24.5,
                            24.53,
                            24.58,
                            24.61,
                            24.64,
                            24.69,
                            24.72,
                            24.75,
                            24.8,
                            24.83,
                            24.86,
                            24.92,
                            25.02,
                            25.1,
                            25.17,
                            25.25,
                            25.33,
                            25.4,
                            25.48,
                            25.56,
                            25.64,
                            25.72,
                            25.8,
                            25.89,
                            25.98,
                            26.08,
                            26.17,
                            26.27,
                            26.36,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "off",
            False,
            id="Off to Off starts cooling in between.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            22.94,
                            22.88,
                            22.83,
                            22.89,
                            22.88,
                            23.06,
                            22.95,
                            23.28,
                            23.23,
                            23.0,
                            22.75,
                            22.52,
                            22.27,
                            22.31,
                            21.67,
                            21.1,
                            20.81,
                            20.56,
                            20.45,
                            20.03,
                            19.86,
                            20.23,
                            20.95,
                            21.23,
                            21.45,
                            21.52,
                            21.52,
                            21.56,
                            21.56,
                            21.6,
                            21.62,
                            21.6,
                            21.67,
                            21.66,
                            21.72,
                        ],
                        [
                            16.62,
                            16.56,
                            16.52,
                            16.45,
                            16.4,
                            16.34,
                            16.3,
                            16.23,
                            16.17,
                            16.11,
                            16.05,
                            15.98,
                            15.914,
                            15.85,
                            15.78,
                            15.72,
                            15.65,
                            15.586,
                            15.516,
                            15.45,
                            15.39,
                            15.32,
                            15.26,
                            15.195,
                            15.13,
                            15.07,
                            15.0,
                            14.94,
                            14.875,
                            14.81,
                            14.75,
                            14.68,
                            14.62,
                            14.56,
                            14.516,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "heat",
            False,
            id="Heat to Off starts cooling and then heating in between.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            20.33,
                            20.48,
                            20.52,
                            20.78,
                            20.83,
                            20.95,
                            21.19,
                            21.56,
                            22.08,
                            22.8,
                            23.69,
                            24.69,
                            25.11,
                            25.62,
                            26.31,
                            27.62,
                            27.67,
                            28.6,
                            29.4,
                            30.77,
                            31.67,
                            32.6,
                            30.72,
                            29.69,
                            30.23,
                            29.7,
                            30.78,
                            29.89,
                            28.66,
                            28.62,
                            29.81,
                            29.64,
                            29.23,
                            28.89,
                            29.25,
                        ],
                        [
                            3.03,
                            3.021,
                            3.012,
                            3.002,
                            2.992,
                            2.984,
                            2.977,
                            2.969,
                            2.96,
                            2.953,
                            2.945,
                            2.938,
                            2.932,
                            2.924,
                            2.916,
                            2.908,
                            2.9,
                            2.893,
                            2.893,
                            2.898,
                            2.904,
                            2.91,
                            2.916,
                            2.922,
                            2.928,
                            2.934,
                            2.94,
                            2.945,
                            2.951,
                            2.957,
                            2.963,
                            2.969,
                            2.975,
                            2.98,
                            2.986,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "heat",
            False,
            id="Keeps on heating even if the outside temperature is colder.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            26.44,
                            26.44,
                            26.45,
                            26.47,
                            26.48,
                            26.5,
                            26.52,
                            26.53,
                            26.55,
                            26.55,
                            26.56,
                            26.56,
                            26.58,
                            26.6,
                            26.61,
                            26.62,
                            26.66,
                            26.69,
                            26.69,
                            26.7,
                            26.72,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.75,
                            26.7,
                            26.27,
                            25.69,
                            25.22,
                            24.88,
                        ],
                        [
                            31.1,
                            31.11,
                            31.14,
                            31.17,
                            31.2,
                            31.22,
                            31.25,
                            31.28,
                            31.31,
                            31.33,
                            31.36,
                            31.33,
                            31.27,
                            31.22,
                            31.16,
                            31.11,
                            31.05,
                            30.98,
                            30.94,
                            30.88,
                            30.81,
                            30.77,
                            30.7,
                            30.64,
                            30.58,
                            30.52,
                            30.45,
                            30.39,
                            30.33,
                            30.27,
                            30.2,
                            30.14,
                            30.08,
                            30.02,
                            29.95,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "off",
            False,
            id="Starts cooling towards the end.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            26.44,
                            26.44,
                            26.45,
                            26.47,
                            26.48,
                            26.5,
                            26.52,
                            26.53,
                            26.55,
                            26.55,
                            26.56,
                            26.56,
                            26.58,
                            26.6,
                            26.61,
                            26.62,
                            26.66,
                            26.69,
                            26.69,
                            26.7,
                            26.72,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.73,
                            26.75,
                            26.7,
                            26.27,
                            25.69,
                            25.22,
                            24.88,
                        ],
                        [
                            31.1,
                            31.11,
                            31.14,
                            31.17,
                            31.2,
                            31.22,
                            31.25,
                            31.28,
                            31.31,
                            31.33,
                            31.36,
                            31.33,
                            31.27,
                            31.22,
                            31.16,
                            31.11,
                            31.05,
                            30.98,
                            30.94,
                            30.88,
                            30.81,
                            30.77,
                            30.7,
                            30.64,
                            30.58,
                            30.52,
                            30.45,
                            30.39,
                            30.33,
                            30.27,
                            30.2,
                            30.14,
                            30.08,
                            30.02,
                            29.95,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "off",
            False,
            id="Change of direction towards the end.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            27.58,
                            27.7,
                            27.8,
                            27.86,
                            27.77,
                            27.42,
                            27.44,
                            27.48,
                            27.56,
                            27.86,
                            27.95,
                            28.02,
                            28.03,
                            28.02,
                            28.0,
                            27.97,
                            27.42,
                            27.4,
                            27.47,
                            27.48,
                            27.78,
                            27.95,
                            28.02,
                            28.02,
                            27.95,
                            27.94,
                            27.9,
                            27.89,
                            27.42,
                            27.36,
                            27.42,
                            27.45,
                            27.8,
                            27.95,
                            27.95,
                        ],
                        [
                            24.1,
                            24.08,
                            24.06,
                            24.05,
                            24.02,
                            24.0,
                            23.98,
                            23.95,
                            23.94,
                            23.92,
                            23.89,
                            23.88,
                            23.86,
                            23.83,
                            23.81,
                            23.8,
                            23.77,
                            23.75,
                            23.73,
                            23.7,
                            23.69,
                            23.67,
                            23.66,
                            23.64,
                            23.62,
                            23.61,
                            23.6,
                            23.58,
                            23.56,
                            23.55,
                            23.53,
                            23.52,
                            23.5,
                            23.47,
                            23.45,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "cool",
            True,
            id="Even though cycling but the temperature variations are minimal.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            26.88,
                            26.86,
                            26.84,
                            26.73,
                            26.69,
                            26.7,
                            26.69,
                            26.72,
                            26.62,
                            26.58,
                            26.53,
                            26.52,
                            26.48,
                            26.47,
                            26.47,
                            26.48,
                            26.52,
                            26.48,
                            26.48,
                            26.44,
                            26.48,
                            26.45,
                            26.44,
                            26.39,
                            26.45,
                            26.53,
                            26.72,
                            27.16,
                            27.5,
                            27.75,
                            27.92,
                            28.06,
                            28.16,
                            28.23,
                            28.31,
                        ],
                        [
                            29.84,
                            29.83,
                            29.83,
                            29.81,
                            29.75,
                            29.7,
                            29.64,
                            29.6,
                            29.53,
                            29.48,
                            29.42,
                            29.38,
                            29.31,
                            29.27,
                            29.2,
                            29.14,
                            29.08,
                            29.02,
                            28.95,
                            28.89,
                            28.83,
                            28.77,
                            28.7,
                            28.64,
                            28.58,
                            28.52,
                            28.45,
                            28.38,
                            28.3,
                            28.22,
                            28.12,
                            28.05,
                            27.97,
                            27.88,
                            27.8,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "off",
            False,
            id="Starts heating in between. Hence should be dropped.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [
                            26.48,
                            26.52,
                            26.56,
                            26.48,
                            26.56,
                            26.61,
                            26.55,
                            26.48,
                            26.52,
                            26.47,
                            26.47,
                            26.44,
                            26.38,
                            26.4,
                            26.4,
                            26.39,
                            26.3,
                            26.27,
                            26.3,
                            26.3,
                            26.28,
                            26.27,
                            26.28,
                            26.19,
                            26.23,
                            26.22,
                            26.2,
                            26.23,
                            26.61,
                            26.95,
                            27.16,
                            27.44,
                            27.62,
                            27.8,
                            27.94,
                            28.03,
                        ],
                        [
                            27.78,
                            27.72,
                            27.66,
                            27.6,
                            27.53,
                            27.47,
                            27.4,
                            27.36,
                            27.31,
                            27.27,
                            27.22,
                            27.17,
                            27.12,
                            27.06,
                            27.02,
                            26.97,
                            26.92,
                            26.88,
                            26.83,
                            26.8,
                            26.86,
                            26.94,
                            27.0,
                            27.06,
                            27.14,
                            27.2,
                            27.28,
                            27.34,
                            27.4,
                            27.48,
                            27.55,
                            27.61,
                            27.56,
                            27.52,
                            27.45,
                            27.4,
                        ],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "off",
            False,
            id="Changing direction in between.",
        ),
    ],
)
def test_room_temperature_behaving_like_off_mode(target, mode_hist, result):
    assert analyze.room_temperature_behaving_like_off_mode(target, mode_hist) == result


@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame([24], columns=["temperature"]),
            "heat",
            29,
            22,
            True,
            id="Single length (5 min) samples shouldn't be dropped because of "
            "filtering. Sample length is too insignificant to make correct judgement.",
        ),
        pytest.param(
            pd.DataFrame([24, 24.2, 24.3, 24.4], columns=["temperature"]),
            "heat",
            25,
            24,
            False,
            id="Small samples behave just like long samples. "
            "In this case it is heating too fast, hence dropped.",
        ),
        pytest.param(
            pd.DataFrame([24, 23.9, 23.8, 23.6], columns=["temperature"]),
            "heat",
            25,
            24,
            True,
            id="Small samples behave just like long samples. "
            "In this case it is cooling as expected.",
        ),
        pytest.param(
            pd.DataFrame([24, 23.7, 23.5, 23.4], columns=["temperature"]),
            "cool",
            25,
            25,
            False,
            id="Small samples behave just like long samples. "
            "Too much variation within 20 minutes, dropped.",
        ),
        pytest.param(
            pd.DataFrame([24, 23.7, 24, 24.1], columns=["temperature"]),
            "cool",
            24,
            25,
            False,
            id="Small samples behave just like long samples. "
            "Starts with cooling then heats suddenly, dropped",
        ),
    ],
)
def test_room_temperature_behaving_like_cool_mode(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_cool_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    27.02,
                    26.16,
                    25.58,
                    25.19,
                    24.81,
                    24.98,
                    24.88,
                    24.86,
                    24.66,
                    24.48,
                    24.36,
                    24.33,
                    24.16,
                    24.08,
                    24.02,
                    23.92,
                    23.92,
                    23.8,
                    23.72,
                    23.72,
                    23.7,
                    23.72,
                    23.66,
                    23.66,
                    23.56,
                    23.53,
                    23.42,
                ],
                columns=["temperature"],
            ),
            "off",
            16,
            16,
            True,
            id="Going from off to dry will cause decrease in temperature with minor heat bumps.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    23.5,
                    23.58,
                    23.55,
                    23.5,
                    23.45,
                    23.38,
                    23.38,
                    23.3,
                    23.33,
                    23.34,
                    23.31,
                    23.34,
                    23.42,
                    23.53,
                    23.67,
                    23.72,
                    23.73,
                    23.72,
                    23.64,
                    23.58,
                    23.48,
                    23.44,
                ],
                columns=["temperature"],
            ),
            "off",
            25,
            25,
            True,
            id="Temperature doesn't vary too much from Off to Dry.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24.06,
                    23.48,
                    23.25,
                    23.2,
                    22.9,
                    22.56,
                    22.47,
                    22.4,
                    22.25,
                    22.02,
                    21.81,
                    21.7,
                    21.78,
                    21.67,
                    21.75,
                    21.55,
                    21.33,
                    21.14,
                    21.7,
                    21.97,
                    22.27,
                    22.16,
                    22.45,
                    22.42,
                    22.45,
                    22.39,
                    22.39,
                    22.36,
                    22.38,
                    22.27,
                    22.28,
                    22.27,
                    22.27,
                    22.22,
                    22.12,
                ],
                columns=["temperature"],
            ),
            "off",
            21,
            21,
            False,
            id="Temperature starts cooling and then heating.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    25.27,
                    25.64,
                    25.86,
                    25.98,
                    26.22,
                    26.17,
                    26.31,
                    26.23,
                    26.3,
                    26.17,
                    26.27,
                    26.19,
                    26.23,
                    26.19,
                    26.14,
                    26.1,
                    26.1,
                    26.08,
                    26.02,
                    26.03,
                    26.0,
                    26.02,
                    25.95,
                    25.98,
                    25.94,
                    25.98,
                    25.89,
                    25.94,
                    25.83,
                    25.89,
                    25.84,
                    25.83,
                    25.78,
                    25.8,
                    25.77,
                ],
                columns=["temperature"],
            ),
            "off",
            26,
            26,
            False,
            id="Temperature starts heating and then cooling.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    26.44,
                    25.64,
                    25.81,
                    25.83,
                    25.42,
                    25.8,
                    25.72,
                    25.89,
                    26.14,
                    25.92,
                    26.06,
                    25.97,
                    25.98,
                    26.17,
                    26.33,
                    26.31,
                    26.45,
                    26.38,
                    26.39,
                    26.45,
                    26.34,
                    26.45,
                    26.45,
                    26.44,
                    26.56,
                    26.4,
                ],
                columns=["temperature"],
            ),
            "dry",
            29,
            30,
            True,
            id="Set Temperature moving from 29 -> 30 with minimal variation",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    25.42,
                    25.28,
                    25.1,
                    25.06,
                    25.14,
                    25.3,
                    25.47,
                    25.61,
                    25.75,
                    25.9,
                    26.06,
                ],
                columns=["temperature"],
            ),
            "dry",
            30,
            27,
            False,
            id="Set Temperature moving from 30 -> 27 and starts heating",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    30.52,
                    29.03,
                    27.83,
                    26.94,
                    26.11,
                    25.42,
                    24.88,
                    24.36,
                    23.95,
                    24.39,
                    24.08,
                    24.16,
                    24.16,
                ],
                columns=["temperature"],
            ),
            "dry",
            25,
            25,
            False,
            id="Set temperature remaining constant and the room temperature varying too much",
        ),
    ],
)
def test_room_temperature_behaving_like_dry_mode(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_dry_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.xfail(
    reason="Trade-off between controlling bad samples and allowing good samples."
    " It is better to drop some of the good samples than to loose the "
    "control over bad samples",
    strict=True,
)
@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    30.2,
                    29.06,
                    27.92,
                    27.11,
                    26.44,
                    25.7,
                    25.05,
                    24.47,
                    23.89,
                    24.22,
                    24.08,
                    24.0,
                    24.1,
                    23.64,
                    24.02,
                    23.55,
                ],
                columns=["temperature"],
            ),
            "off",
            30,
            25,
            True,
            id="Being dropped because of cooling and then heating. Increase the "
            "parameters - SIGNIFICANT_TEMPERATURE_DELTA_MOVEMENT, xxx "
            "to accept this sample.",
        ),
        pytest.param(
            pd.DataFrame([27.75, 27.9, 28.08, 27.98], columns=["temperature"]),
            "dry",
            26,
            25,
            True,
            id="Could have kept, but heating too fast.",
        ),
    ],
)
def test_dry_mode_samples_which_were_good_samples_but_are_still_dropped(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_dry_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    18.27,
                    19.36,
                    20.06,
                    20.61,
                    20.78,
                    21.0,
                    21.11,
                    21.23,
                    21.3,
                    21.34,
                    21.38,
                    21.44,
                    21.44,
                    21.44,
                    21.44,
                    21.42,
                    21.44,
                    21.45,
                    21.45,
                    21.5,
                    21.53,
                    21.53,
                    21.55,
                    21.55,
                    21.48,
                    21.52,
                    21.52,
                    21.52,
                    21.53,
                    21.55,
                    21.55,
                    21.53,
                    21.55,
                    21.58,
                    21.58,
                ],
                columns=["temperature"],
            ),
            "cool",
            17,
            16,
            True,
            id="Going from cooling mode to heating mode. We expect the room to heat."
            "And its behaving as expected. Hence shouldn't be dropped",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    20.44,
                    20.69,
                    19.77,
                    18.56,
                    17.97,
                    17.6,
                    17.48,
                    17.62,
                    17.77,
                    18.08,
                    18.45,
                    18.19,
                    17.95,
                    17.94,
                    18.11,
                    18.14,
                    18.16,
                    18.19,
                    18.42,
                    18.27,
                    18.31,
                    18.38,
                    18.36,
                    18.39,
                    18.44,
                    18.42,
                    18.5,
                    18.5,
                    18.42,
                    18.73,
                    18.9,
                    19.03,
                    18.94,
                    18.94,
                    18.73,
                ],
                columns=["temperature"],
            ),
            "heat",
            26,
            27,
            False,
            id="Should drop temperature is getting colder even at higher set temperature",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    20.11,
                    20.11,
                    20.11,
                    20.1,
                    20.11,
                    20.19,
                    20.16,
                    20.12,
                    20.1,
                    20.12,
                    20.2,
                    20.11,
                    19.66,
                    18.47,
                    18.67,
                    18.78,
                    18.83,
                    18.83,
                    18.86,
                    19.02,
                    19.17,
                    19.33,
                    19.38,
                    19.45,
                    19.48,
                    19.53,
                    19.6,
                ],
                columns=["temperature"],
            ),
            "heat",
            88,
            88,
            False,
            id="Has been on this state for more than 3 hours. We expect minimal variation. "
            "However, we notice a sudden temperature variation. Hence, dropped.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    18.73,
                    18.75,
                    18.73,
                    18.69,
                    18.62,
                    18.58,
                    18.56,
                    18.48,
                    18.45,
                    18.42,
                    18.36,
                    18.34,
                    18.34,
                    18.34,
                    18.34,
                    18.38,
                    18.45,
                    18.6,
                    18.69,
                    18.66,
                    18.61,
                    18.55,
                    18.45,
                    18.38,
                    18.34,
                    18.3,
                    18.3,
                    18.36,
                    18.44,
                    18.8,
                    19.11,
                    19.22,
                    19.06,
                    18.9,
                    18.73,
                ],
                columns=["temperature"],
            ),
            "heat",
            62,
            61,
            True,
            id="Going from Higher set temperature to lower set temperature."
            "We should drop samples which show some weird behaviour like "
            "change of direction. This sample is showing change of direction "
            "But its not a permanent change of direction or a substantial "
            "change of direction. The change is much more due to noise. "
            "Hence we keep this sample.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    26.55,
                    26.62,
                    26.73,
                    26.84,
                    26.97,
                    27.05,
                    27.17,
                    26.7,
                    25.14,
                    24.12,
                    24.0,
                    23.42,
                    23.19,
                    22.75,
                    22.94,
                    22.94,
                    22.84,
                    22.5,
                    22.34,
                    22.11,
                    21.98,
                    22.34,
                    22.4,
                    22.42,
                    22.67,
                    23.69,
                    24.69,
                    25.48,
                    25.95,
                    26.02,
                    25.89,
                    25.38,
                    24.39,
                    24.03,
                    23.52,
                ],
                columns=["temperature"],
            ),
            "heat",
            18,
            16,
            False,
            id="Should drop because temperature getting colder then hotter",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    18.98,
                    20.03,
                    20.61,
                    20.88,
                    20.89,
                    21.19,
                    21.45,
                    21.7,
                    21.86,
                    22.1,
                    22.5,
                    22.89,
                    22.98,
                    22.86,
                    22.81,
                    22.8,
                    22.86,
                    22.72,
                    23.1,
                    22.72,
                    22.9,
                    23.02,
                    23.08,
                    23.11,
                    23.12,
                    23.23,
                    23.05,
                    22.38,
                    21.75,
                    21.36,
                    21.11,
                    21.06,
                    21.73,
                    21.77,
                    22.2,
                ],
                columns=["temperature"],
            ),
            "heat",
            72,
            74,
            False,
            id="Should drop because getting hotter then starts getting colder",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    22.16,
                    22.27,
                    22.33,
                    22.4,
                    22.45,
                    22.48,
                    22.5,
                    22.56,
                    22.6,
                    22.64,
                    22.69,
                    22.78,
                    22.8,
                    22.8,
                    22.8,
                    22.8,
                    22.8,
                    22.8,
                    22.8,
                    22.81,
                    22.8,
                    22.78,
                    22.75,
                    22.73,
                    22.73,
                    22.7,
                    22.69,
                    22.66,
                    22.64,
                    22.62,
                    22.6,
                    22.56,
                    22.53,
                    22.5,
                    22.47,
                ],
                columns=["temperature"],
            ),
            "heat",
            19,
            18,
            True,
            id="Samples with minimal temperature variation shouldn't be dropped",
        ),
    ],
)
def test_room_temperature_behaving_like_heat_mode(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_heat_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.xfail(
    reason="Trade-off between controlling bad samples and allowing good samples "
    "and time taken for programming these rules.",
    strict=True,
)
@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    21.42,
                    21.17,
                    21.14,
                    21.27,
                    21.45,
                    21.36,
                    21.44,
                    21.2,
                    20.95,
                    20.78,
                    20.7,
                    20.9,
                    21.16,
                    21.05,
                    20.9,
                    21.0,
                    20.97,
                    20.88,
                    21.33,
                    21.81,
                    22.02,
                    21.83,
                ],
                columns=["temperature"],
            ),
            "heat",
            19,
            20,
            True,
            id="Good sample but cools more than expected. Set temperature "
            "moves from 19 to 20, so we expect it to heat",
        ),
        pytest.param(
            pd.DataFrame(
                [20.81, 20.72, 20.56, 20.36, 20.2, 20.08], columns=["temperature"]
            ),
            "heat",
            26,
            26,
            True,
            id="Varying too much for such a short range. Since its a short sample "
            "therefore kind of hard to tell if it would have kept varying if "
            "it was a longer sample. Dropping this for now. Trade-off between "
            "letting some good samples drop vs letting some bad samples in.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    17.27,
                    17.3,
                    17.34,
                    17.45,
                    17.44,
                    17.56,
                    17.52,
                    17.5,
                    17.64,
                    17.61,
                    17.56,
                    17.61,
                    17.64,
                    17.64,
                    17.72,
                    17.7,
                    17.7,
                    17.7,
                    17.69,
                    17.62,
                    18.2,
                    18.55,
                    18.7,
                    18.88,
                    19.08,
                    19.39,
                    19.42,
                    19.55,
                    19.53,
                    19.6,
                    19.55,
                    19.56,
                    19.52,
                    19.48,
                    19.59,
                ],
                columns=["temperature"],
            ),
            "off",
            23,
            22,
            False,
            id="Bad sample. Set temperature changes from 23 to 22. "
            "It keeps on heating slightly then abruptly heats too much "
            "and then stabilizes. But since this sample never changes "
            "the direction in between i.e. keeps on heating only therefore "
            "we don't drop it. Very small number of samples like this "
            "hence this case is not being handled.",
        ),
    ],
)
def test_heating_mode_samples_which_should_have_been_dropped_but_are_kept_and_vice_versa(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_heat_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.parametrize(
    "target, mode_hist, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    25.89,
                    26.02,
                    26.05,
                    26.06,
                    26.05,
                    26.08,
                    26.12,
                    26.19,
                    26.2,
                    26.28,
                    26.31,
                    26.31,
                    26.34,
                    26.33,
                    26.31,
                    26.31,
                    26.31,
                    26.33,
                    26.31,
                    26.34,
                    26.44,
                    26.4,
                    25.94,
                    25.34,
                    24.94,
                    24.81,
                    24.52,
                    24.44,
                    24.56,
                    24.77,
                    24.95,
                    25.02,
                    25.12,
                    25.2,
                    25.28,
                ],
                columns=["temperature"],
            ),
            "dry",
            False,
            id="Starts cooling in between",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    18.8,
                    18.78,
                    18.8,
                    18.81,
                    18.81,
                    18.83,
                    18.84,
                    18.84,
                    18.84,
                    18.86,
                    18.88,
                    18.9,
                    19.05,
                    19.19,
                    19.47,
                    19.88,
                    20.16,
                    20.48,
                    20.56,
                    20.6,
                    20.77,
                    20.95,
                    21.17,
                    21.38,
                    21.6,
                    21.8,
                    22.02,
                    22.31,
                    22.33,
                    22.23,
                    22.23,
                    22.2,
                    22.17,
                ],
                columns=["temperature"],
            ),
            "fan",
            False,
            id="Too much variation for going from stagnant mode like fan/off to fan",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [22.05, 22.19, 22.34, 22.42, 22.61, 22.73, 22.84, 22.94],
                        [22.34, 22.28, 22.2, 22.16, 22.08, 22.02, 21.95, 21.88],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "heat",
            False,
            id="Continue heating even even after moving to fan with outside "
            "temperature being colder than indoor.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    20.9,
                    21.28,
                    21.53,
                    21.8,
                    21.9,
                    21.97,
                    22.03,
                    22.12,
                    22.19,
                    22.3,
                    22.34,
                    22.44,
                    22.52,
                    22.55,
                    22.61,
                    22.69,
                    22.7,
                    22.77,
                    22.81,
                    22.81,
                    22.88,
                    22.92,
                    22.9,
                    22.97,
                    23.02,
                    23.05,
                    23.06,
                    23.11,
                    23.14,
                    23.16,
                    23.2,
                    23.2,
                    23.27,
                    23.2,
                    23.3,
                ],
                columns=["temperature"],
            ),
            "cool",
            True,
            id="Going from cool to fan will increase the room the temperature "
            "irrespective of the outside temperature.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    27.7,
                    27.7,
                    27.69,
                    27.62,
                    27.62,
                    27.69,
                    27.7,
                    27.77,
                    27.78,
                    27.84,
                    27.92,
                    27.95,
                    27.98,
                    27.95,
                    28.02,
                    28.06,
                    28.06,
                    28.05,
                    28.02,
                    28.05,
                    28.14,
                    28.12,
                    28.08,
                    28.06,
                    28.14,
                    28.2,
                    28.16,
                    28.14,
                    28.12,
                    28.14,
                    28.19,
                    28.14,
                    28.16,
                    28.14,
                    28.19,
                ],
                columns=["temperature"],
            ),
            "off",
            True,
            id="Going from off to fan is similar to going from fan to fan. "
            "It shouldn't impact the room temperature much.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [22.64, 22.69, 22.7, 22.7, 22.78, 22.89, 23.0, 23.11, 23.19],
                        [23.19, 23.28, 23.38, 23.47, 23.56, 23.66, 23.75, 23.84, 23.9],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "heat",
            True,
            id="Going from heat to fan when outside weather is hotter than inside "
            "will result in increase in temperature or stagnation of temperature "
            "in fan mode.",
        ),
        pytest.param(
            pd.DataFrame(
                list(
                    zip(
                        [21.45, 20.77, 20.52, 20.27, 20.12, 20.05],
                        [1.278, 1.221, 1.164, 1.108, 1.051, 1.008],
                    )
                ),
                columns=["temperature", "weather_temperature_out"],
            ),
            "heat",
            True,
            id="Going from heat to fan when outside weather is colder than inside "
            "will result in decrease in temperature or stagnation of temperature "
            "in fan mode.",
        ),
    ],
)
def test_fan_mode_samples(target, mode_hist, result):
    assert analyze.room_temperature_behaving_like_fan_mode(target, mode_hist) == result


@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    22.27,
                    21.61,
                    21.25,
                    21.06,
                    20.81,
                    20.72,
                    20.6,
                    20.52,
                    20.45,
                    20.36,
                    20.31,
                    20.27,
                    20.16,
                    20.16,
                    20.19,
                    20.19,
                    20.19,
                    20.17,
                    20.19,
                    20.1,
                    20.19,
                    20.16,
                    20.1,
                    20.06,
                    20.17,
                    20.06,
                    20.16,
                    20.11,
                    20.06,
                    20.1,
                    20.11,
                    20.05,
                    20.16,
                    20.16,
                    20.11,
                ],
                columns=["temperature"],
            ),
            "auto",
            72,
            72,
            False,
            id="Only limited variations allowed when moving between the same setting. "
            "Here variations are too much. Hence we drop it.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    26.2,
                    26.27,
                    26.31,
                    26.38,
                    26.4,
                    26.45,
                    26.52,
                    26.55,
                    26.69,
                    27.11,
                    26.52,
                    26.08,
                    25.83,
                    25.4,
                    25.22,
                    24.73,
                ],
                columns=["temperature"],
            ),
            "auto",
            20,
            19,
            False,
            id="Bad sample because starts heating and then cooling.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    22.12,
                    22.45,
                    22.66,
                    22.12,
                    21.94,
                    21.77,
                    21.56,
                    21.25,
                    21.19,
                    21.53,
                    21.77,
                    21.53,
                    21.33,
                    21.2,
                    21.08,
                    21.02,
                    20.95,
                    20.88,
                    20.88,
                    20.89,
                    21.17,
                    21.52,
                    21.55,
                    21.34,
                    21.2,
                    21.12,
                    21.2,
                    21.55,
                    21.77,
                    21.56,
                    21.36,
                    21.25,
                    21.45,
                    21.58,
                    21.47,
                ],
                columns=["temperature"],
            ),
            "cool",
            20,
            23,
            True,
            id="Going from cool to auto. Starts cooling and then slightly heating. "
            "However, the change in trend is minor.",
        ),
    ],
)
def test_auto_mode_samples(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_auto_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.xfail(
    reason="We are not currently handling the following cases.", strict=True
)
@pytest.mark.parametrize(
    "target, mode_hist, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    22.02,
                    22.02,
                    22.02,
                    21.83,
                    21.84,
                    21.81,
                    21.88,
                    21.94,
                    22.02,
                    22.02,
                    22.02,
                    22.02,
                    21.98,
                    22.0,
                    22.02,
                    22.02,
                    22.17,
                    22.23,
                    22.31,
                    22.42,
                    22.48,
                    22.56,
                    22.67,
                    22.77,
                    22.88,
                    22.9,
                    22.98,
                    23.1,
                    23.16,
                    23.23,
                    23.28,
                ],
                columns=["temperature"],
            ),
            "auto",
            17,
            16,
            False,
            id="Bad sample because set temperature is going from 17 to 16. "
            "If the auto mode was behaving like cool mode, which it was in this case, "
            "then we expect the temperature to go down. But it went up."
            "However, this wasn't the case of change in direction because the sample "
            "keeps heating or maintaining the temperature. But we wanted the sample to "
            "go down and cool the room (auto was behaving like cool here).",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    23.55,
                    23.53,
                    23.53,
                    23.47,
                    23.45,
                    23.44,
                    23.38,
                    23.34,
                    23.31,
                    23.23,
                    23.17,
                    23.12,
                    23.1,
                    23.08,
                    23.2,
                    22.9,
                    22.47,
                    22.05,
                    22.05,
                    22.05,
                    21.97,
                    21.84,
                    21.92,
                    21.84,
                    21.81,
                    21.77,
                    21.78,
                    21.7,
                    21.62,
                    21.62,
                    21.7,
                    21.8,
                    21.81,
                    21.8,
                    21.73,
                ],
                columns=["temperature"],
            ),
            "cool",
            64,
            64,
            False,
            id="It was cooling normally but then suddenly cools a lot."
            "We are not handling the case where it suddenly spikes without "
            "a change in the direction.",
        ),
    ],
)
def test_auto_mode_samples_which_are_not_being_handled_currently(
    target, mode_hist, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.room_temperature_behaving_like_auto_mode(
            target, mode_hist, previous_set_temperature, set_temperature
        )
        == result
    )


@pytest.mark.parametrize(
    "target, result",
    [
        pytest.param(
            pd.DataFrame(
                [24, 24.1, 24.12, 24.13, 24.14, 24.17, 24.18, 24.19, 24.19, 24.2],
                columns=["temperature"],
            ),
            True,
            id="almost constant temperature series",
        ),
        pytest.param(
            pd.DataFrame(
                [24, 24.1, 24.12, 24.15, 24.16, 24.17, 24.2, 24.21, 24.23, 24.3, 24.31],
                columns=["temperature"],
            ),
            False,
            id="high variance temperature series considering the "
            "length and allowed variation i.e. 1 degree allowed for 36 samples",
        ),
    ],
)
def test_is_temperature_variation_minimal(target, result):
    assert (
        analyze.is_temperature_variation_minimal(
            target, allowed_variation_in_three_hours=1
        )
        == result
    )


@pytest.mark.parametrize(
    "temperature_series, result",
    [
        pytest.param(
            np.array([24, 24.5, 24.7, 24.8, 24.9, 25.0, 25.1, 25.2, 25.4]),
            True,
            id="if temperature heats too much within 5 minutes i.e. 24 to 24.5",
        ),
        pytest.param(
            np.array([24, 24.15, 24.3, 24.4, 25.5, 25.7, 25.9, 26.0]),
            True,
            id="if the temperature heats steadily and quickly",
        ),
        pytest.param(
            np.array(
                [24, 24.1, 24.2, 24.23, 24.3, 24.35, 24.4, 24.45, 24.5, 24.54, 24.6]
            ),
            False,
            id="if the temperature doesn't heat quickly",
        ),
        pytest.param(
            np.array([24, 23.9, 23.8, 23.7, 23.6, 23.4, 23.3, 23.2, 23.1, 23.0, 22.9]),
            False,
            id="if the temperature cools",
        ),
        pytest.param(
            np.array(
                [24, 24.1, 24.2, 24.1, 24.1, 24.2, 24.1, 24.2, 24.25, 24.2, 24.15, 24.3]
            ),
            False,
            id="if the temperature heats intermittently and cools intermittently but slowly",
        ),
    ],
)
def test_is_temperature_getting_hotter(temperature_series, result):
    temperature_deltas = temperature_series[1:] - temperature_series[:-1]
    assert analyze.is_temperature_getting_hotter(temperature_deltas) == result


@pytest.mark.parametrize(
    "target, previous_set_temperature, current_set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    24.2,
                    24.5,
                    24.6,
                    24.8,
                    24.9,
                    25.1,
                    25.4,
                    26,
                    26.2,
                    26.8,
                    27,
                    27.1,
                    27.5,
                ],
                columns=["temperature"],
            ),
            24,
            25,
            True,
            id="too much variation (in the right direction) for a single degree",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    19,
                    19.2,
                    19.4,
                    20,
                    20.5,
                    21,
                    21.5,
                    22,
                    23.5,
                    24,
                    24.5,
                    25,
                    25.5,
                    26,
                    26.5,
                    27,
                    27.5,
                    28,
                ],
                columns=["temperature"],
            ),
            18,
            30,
            True,
            id="too much variation (in the right direction) within a very short time "
            "for a 12 degrees set temperature change",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    20.9,
                    21.28,
                    21.53,
                    21.8,
                    21.9,
                    21.97,
                    22.03,
                    22.12,
                    22.19,
                    22.3,
                    22.34,
                    22.44,
                    22.52,
                    22.55,
                    22.61,
                    22.69,
                    22.7,
                    22.77,
                    22.81,
                    22.81,
                    22.88,
                    22.92,
                    22.9,
                    22.97,
                    23.02,
                    23.05,
                    23.06,
                    23.11,
                    23.14,
                    23.16,
                    23.2,
                    23.2,
                    23.27,
                    23.2,
                    23.3,
                ],
                columns=["temperature"],
            ),
            20,
            23,
            False,
            id="Allowed variation for a change of 3 degrees in set temperature",
        ),
    ],
)
def test_is_temperature_variation_more_than_expected_variation_for_change_in_the_set_temperature(
    target, previous_set_temperature, current_set_temperature, result
):
    assert (
        analyze.is_high_temperature_variation_per_degree_set_temperature(
            target, previous_set_temperature, current_set_temperature
        )
        == result
    )


@pytest.mark.parametrize(
    "target, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    24.1,
                    24.2,
                    24.2,
                    24.3,
                    24.34,
                    24.4,
                    24.44,
                    24.5,
                    24.51,
                    24.54,
                    24.6,
                ],
                columns=["temperature"],
            ),
            False,
            id="temperature variations are minimal",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    24.15,
                    24.25,
                    24.5,
                    24.55,
                    24.75,
                    24.5,
                    24,
                    23.5,
                    23.2,
                    23,
                    22.75,
                    22.5,
                ],
                columns=["temperature"],
            ),
            True,
            id="temperature starts heating first and then starts cooling",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    23.8,
                    23.5,
                    23.3,
                    23,
                    22.74,
                    22.5,
                    22.25,
                    22,
                    22.4,
                    22.8,
                    23.2,
                    23.6,
                    23.8,
                    24,
                ],
                columns=["temperature"],
            ),
            True,
            id="temperature starts cooling first and then starts heating",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    23.9,
                    23.8,
                    23.7,
                    23.6,
                    23.55,
                    23.51,
                    23.5,
                    23.5,
                    23.4,
                    23.3,
                    23.2,
                    23,
                ],
                columns=["temperature"],
            ),
            False,
            id="temperature cools only",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24,
                    24.1,
                    24.15,
                    24.2,
                    24.25,
                    24.3,
                    24.35,
                    24.4,
                    24.45,
                    24.5,
                    24.6,
                    24.65,
                    24.7,
                    25,
                ],
                columns=["temperature"],
            ),
            False,
            id="temperature heats only",
        ),
    ],
)
def test_is_temperature_changing_direction_in_between(target, result):
    assert analyze.is_temperature_changing_direction_in_between(target) == result


@pytest.mark.parametrize(
    "streak, result",
    [
        pytest.param(
            np.array([0.15, 0.2, 0.1]),
            True,
            id="cumulative mean is significant if mean of any cumulative number "
            "is more than SIGNIFICANT_TEMPERATURE_DELTA_MOVEMENT",
        ),
        pytest.param(
            np.array([0.35, 0.2, 0.1]),
            True,
            id="value at index 0 is greater than 0.25 implying that streak is significant",
        ),
        pytest.param(
            np.array([0.01, 0.12, 0.15, 0.17, 0.19]),
            False,
            id="the variations are insignificant",
        ),
    ],
)
def test_is_any_of_the_cumulative_mean_significant(streak, result):
    assert analyze.is_any_of_the_cumulative_mean_significant(streak) == result


@pytest.mark.parametrize(
    "streak, result",
    [
        pytest.param(
            np.array([2.0, 4.0, 6.0]),
            [2.0, 3.0, 4.0],
            id="cumulative mean of positive numbers",
        )
    ],
)
def test_calculate_cumulative_mean(streak, result):
    assert analyze.calculate_cumulative_mean(streak) == result


@pytest.mark.xfail(
    reason="The below samples should be dropped but they are not. We don't cover the case "
    "where samples jump suddenly without changing the direction. For "
    "example, if you were heating and then suddenly heated a lot and then continue "
    "heating normally, we wouldn't drop it. Since there are only a few of such samples "
    "therefore we are not covering it.",
    strict=True,
)
@pytest.mark.parametrize(
    "target, previous_set_temperature, set_temperature, result",
    [
        pytest.param(
            pd.DataFrame(
                [
                    20,
                    20.1,
                    20.2,
                    20.23,
                    20.28,
                    20.3,
                    20.35,
                    20.4,
                    20.6,
                    20.8,
                    20.9,
                    21.0,
                    21.2,
                    21.4,
                    21.6,
                    21.9,
                    22.2,
                    22.4,
                    22.8,
                    23,
                    23.3,
                    23.6,
                    23.9,
                    24.1,
                    24.12,
                    24.13,
                    24.16,
                    24.18,
                    24.18,
                    24.19,
                    24.2,
                    24.21,
                    24.22,
                    24.24,
                    24.25,
                    24.26,
                ],
                columns=["temperature"],
            ),
            23,
            28,
            True,
            id="This is a bad sample because there is a heat spike in between. In general, "
            "sample shouldn't have any spikes in between. Spikes are expected at the start "
            "only. If there is a spike towards the middle or the end then that means "
            "the settings must have changed. We are still keeping this sample because "
            "there aren't that many of such samples.",
        ),
        pytest.param(
            pd.DataFrame(
                [
                    24.26,
                    24.25,
                    24.24,
                    24.22,
                    24.21,
                    24.2,
                    24.19,
                    24.18,
                    24.18,
                    24.16,
                    24.13,
                    24.12,
                    24.1,
                    23.9,
                    23.6,
                    23.3,
                    23,
                    22.8,
                    22.4,
                    22.2,
                    21.9,
                    21.6,
                    21.4,
                    21.2,
                    21.0,
                    20.9,
                    20.8,
                    20.6,
                    20.4,
                    20.35,
                    20.3,
                    20.28,
                    20.23,
                    20.2,
                    20.1,
                    20,
                ],
                columns=["temperature"],
            ),
            28,
            23,
            True,
            id="This is a bad sample which should be dropped but isn't. "
            "It starts cooling and then suddenly cools too much and "
            "then stabilises. This generally happens upon change of setting.",
        ),
    ],
)
def test_samples_which_spike_without_changing_direction(
    target, previous_set_temperature, set_temperature, result
):
    assert (
        analyze.is_temperature_showing_any_weird_behavior(
            target, previous_set_temperature, set_temperature
        )
        == result
    )
